name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Backend Awake
        run: curl -s https://developer-playground-1.onrender.com/health
